### ISSUE TITLE
Improvement: Checkbox to toggle enable/disable of track

### ISSUE THREAD

**Issue by aubergine10** [rumangerst/CSLMusicMod#20]
In the track list panel, tooltip says to double-click a track to disable it.

I feel it would be much better to have a small checkbox (like the blue square thing used in content manager or mod options) at the start of each track entry in the list as it would provide much better visual feedback as to which tracks are enabled/disabled and also make it far more obvious how to enable/disable a track (without relying on tooltip or weird double-click).

**Comment by rumangerst** [comment]
I really would love this, too - But it does not work. Tried it. The UI system offers a list component that does exactly what you can see and nothing else. In a different branch I tried to completely build a better list from ground up. Ended in a massive lag fest.

**Comment by aubergine10** [comment]
Can you update items in the list while it's displayed? Maybe keep the double click thing, but have that checkbox icon change state as visual feedback - not ideal, but at least I will see clearly which items are enabled/disabled.

**Comment by rumangerst** [comment]
I think I might have a solution how to get a checkbox without adding new UI elements

(Writing this down because otherwise I could forget it)
* If content disabling is enabled, always render a checkbox sprite in front of the item
* If the user clicks on an entry, use the mouse position and the position of the control to calculate if the user clicked on the checkbox
* Do action accordingly
